_base_: culane_s0_structured_query_res34_slots32_b8x2_1600x640_bins800_fpn256_l4_dfl_50ep.yaml

seed: 3407

output_dir: outputs/culane_s0_structured_query_res34_slots32_b8x2_1600x640_bins800_fpn256_l4_dfl_full_seed3407_225k

model:
  structured_query:
    use_intra_attention: true

training:
  max_iters: 225000
