_base_: curvelanes_s0_structured_query_base_1600x640_bins800_fpn256_l4_dfl_50ep.yaml

output_dir: outputs/curvelanes_s0_structured_query_dla34_slots32_b8x2_1600x640_bins800_fpn256_l4_dfl_50ep

model:
  backbone_name: dla34
